import 'package:meta/meta.dart';

class Contact {
  static final db_tableName = "contacts";

  static final db_id = "id";   /* unique id generated by MySql */
  static final db_acct_id = "acctid"; /* account id */
  static final db_name = "name"; /* display name */
  static final db_email = "email"; /* email */
  static final db_phnum = "phnum"; /* phone number */
  static final db_last_ct = "lastct"; /* last time that was notified */
  static final db_monitoring = "mon"; /* monitoring (1) or being monitored (0) */

  static final columns = [db_id, db_acct_id, db_name, db_email, db_phnum, db_last_ct, db_monitoring];

  String id, acctid, name, email, phnum, lastct, monitoring;

  Contact({
    @required this.id,
    @required this.acctid,
    @required this.name,
    @required this.email,
    @required this.phnum,
    @required this.lastct,
    @required this.monitoring,
  });

  Contact.fromMap(Map<String, dynamic> map): this (
    id: map[db_id],
    acctid: map[db_acct_id],
    name: map[db_name],
    email: map[db_email],
    phnum: map[db_phnum],
    lastct: map[db_last_ct],
    monitoring: map[db_monitoring],
  );

  Map<String, dynamic> toMap() {
    return {
      db_id: id,
      db_acct_id: acctid,
      db_name: name,
      db_email: email,
      db_phnum: phnum,
      db_last_ct: lastct,
      db_monitoring: monitoring,
    };
  }
}